# Generated by Django 5.1 on 2024-08-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
