# Generated by Django 5.1 on 2024-08-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recipient_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='used_volume',
            field=models.IntegerField(default=0),
        ),
    ]
